spring:
  application:
    name: "delimeat"
  cache:
    caffeine:
      spec: maximumSize=100, expireAfterAccess=10m, expireAfterWrite=1h
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
      indent-output: true
    deserialization:
      read-date-timestamps-as-nanoseconds: false
logging:
  level:
    io.delimeat: INFO
    ROOT: INFO 
---
spring:
  profiles: development
  aop:
    proxy-target-class: true
debug: true
logging:
  level:
    io.delimeat: ALL
    org.springframework.aop.interceptor.CustomizableTraceInterceptor: TRACE
    ROOT: ALL   
    
---    
spring:
  profiles: production
logging:
  level:
    ROOT: INFO
